module.exports = {
  v3Abi: [
    {
      inputs: [
        {
          components: [
            { internalType: "address", name: "governor", type: "address" },
            { internalType: "address", name: "pauseGuardian", type: "address" },
            { internalType: "address", name: "baseToken", type: "address" },
            {
              internalType: "address",
              name: "baseTokenPriceFeed",
              type: "address",
            },
            {
              internalType: "address",
              name: "extensionDelegate",
              type: "address",
            },
            { internalType: "uint64", name: "supplyKink", type: "uint64" },
            {
              internalType: "uint64",
              name: "supplyPerYearInterestRateSlopeLow",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "supplyPerYearInterestRateSlopeHigh",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "supplyPerYearInterestRateBase",
              type: "uint64",
            },
            { internalType: "uint64", name: "borrowKink", type: "uint64" },
            {
              internalType: "uint64",
              name: "borrowPerYearInterestRateSlopeLow",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "borrowPerYearInterestRateSlopeHigh",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "borrowPerYearInterestRateBase",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "storeFrontPriceFactor",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "trackingIndexScale",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "baseTrackingSupplySpeed",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "baseTrackingBorrowSpeed",
              type: "uint64",
            },
            {
              internalType: "uint104",
              name: "baseMinForRewards",
              type: "uint104",
            },
            { internalType: "uint104", name: "baseBorrowMin", type: "uint104" },
            {
              internalType: "uint104",
              name: "targetReserves",
              type: "uint104",
            },
            {
              components: [
                { internalType: "address", name: "asset", type: "address" },
                { internalType: "address", name: "priceFeed", type: "address" },
                { internalType: "uint8", name: "decimals", type: "uint8" },
                {
                  internalType: "uint64",
                  name: "borrowCollateralFactor",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "liquidateCollateralFactor",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "liquidationFactor",
                  type: "uint64",
                },
                { internalType: "uint128", name: "supplyCap", type: "uint128" },
              ],
              internalType: "struct CometConfiguration.AssetConfig[]",
              name: "assetConfigs",
              type: "tuple[]",
            },
          ],
          internalType: "struct CometConfiguration.Configuration",
          name: "config",
          type: "tuple",
        },
      ],
      stateMutability: "nonpayable",
      type: "constructor",
    },
    { inputs: [], name: "Absurd", type: "error" },
    { inputs: [], name: "AlreadyInitialized", type: "error" },
    { inputs: [], name: "BadAsset", type: "error" },
    { inputs: [], name: "BadDecimals", type: "error" },
    { inputs: [], name: "BadDiscount", type: "error" },
    { inputs: [], name: "BadMinimum", type: "error" },
    { inputs: [], name: "BadPrice", type: "error" },
    { inputs: [], name: "BorrowCFTooLarge", type: "error" },
    { inputs: [], name: "BorrowTooSmall", type: "error" },
    { inputs: [], name: "InsufficientReserves", type: "error" },
    { inputs: [], name: "InvalidInt104", type: "error" },
    { inputs: [], name: "InvalidInt256", type: "error" },
    { inputs: [], name: "InvalidUInt104", type: "error" },
    { inputs: [], name: "InvalidUInt128", type: "error" },
    { inputs: [], name: "InvalidUInt64", type: "error" },
    { inputs: [], name: "LiquidateCFTooLarge", type: "error" },
    { inputs: [], name: "NegativeNumber", type: "error" },
    { inputs: [], name: "NoSelfTransfer", type: "error" },
    { inputs: [], name: "NotCollateralized", type: "error" },
    { inputs: [], name: "NotForSale", type: "error" },
    { inputs: [], name: "NotLiquidatable", type: "error" },
    { inputs: [], name: "Paused", type: "error" },
    { inputs: [], name: "SupplyCapExceeded", type: "error" },
    { inputs: [], name: "TimestampTooLarge", type: "error" },
    { inputs: [], name: "TooManyAssets", type: "error" },
    { inputs: [], name: "TooMuchSlippage", type: "error" },
    { inputs: [], name: "TransferInFailed", type: "error" },
    { inputs: [], name: "TransferOutFailed", type: "error" },
    { inputs: [], name: "Unauthorized", type: "error" },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "absorber",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "borrower",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "asset",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "collateralAbsorbed",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "usdValue",
          type: "uint256",
        },
      ],
      name: "AbsorbCollateral",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "absorber",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "borrower",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "basePaidOut",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "usdValue",
          type: "uint256",
        },
      ],
      name: "AbsorbDebt",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "buyer",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "asset",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "baseAmount",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "collateralAmount",
          type: "uint256",
        },
      ],
      name: "BuyCollateral",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "bool",
          name: "supplyPaused",
          type: "bool",
        },
        {
          indexed: false,
          internalType: "bool",
          name: "transferPaused",
          type: "bool",
        },
        {
          indexed: false,
          internalType: "bool",
          name: "withdrawPaused",
          type: "bool",
        },
        {
          indexed: false,
          internalType: "bool",
          name: "absorbPaused",
          type: "bool",
        },
        {
          indexed: false,
          internalType: "bool",
          name: "buyPaused",
          type: "bool",
        },
      ],
      name: "PauseAction",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "from",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "dst",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "amount",
          type: "uint256",
        },
      ],
      name: "Supply",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "from",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "dst",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "asset",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "amount",
          type: "uint256",
        },
      ],
      name: "SupplyCollateral",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "from",
          type: "address",
        },
        { indexed: true, internalType: "address", name: "to", type: "address" },
        {
          indexed: false,
          internalType: "uint256",
          name: "amount",
          type: "uint256",
        },
      ],
      name: "Transfer",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "from",
          type: "address",
        },
        { indexed: true, internalType: "address", name: "to", type: "address" },
        {
          indexed: true,
          internalType: "address",
          name: "asset",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "amount",
          type: "uint256",
        },
      ],
      name: "TransferCollateral",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "src",
          type: "address",
        },
        { indexed: true, internalType: "address", name: "to", type: "address" },
        {
          indexed: false,
          internalType: "uint256",
          name: "amount",
          type: "uint256",
        },
      ],
      name: "Withdraw",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "src",
          type: "address",
        },
        { indexed: true, internalType: "address", name: "to", type: "address" },
        {
          indexed: true,
          internalType: "address",
          name: "asset",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "amount",
          type: "uint256",
        },
      ],
      name: "WithdrawCollateral",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: "address", name: "to", type: "address" },
        {
          indexed: false,
          internalType: "uint256",
          name: "amount",
          type: "uint256",
        },
      ],
      name: "WithdrawReserves",
      type: "event",
    },
    { stateMutability: "payable", type: "fallback" },
    {
      inputs: [
        { internalType: "address", name: "absorber", type: "address" },
        { internalType: "address[]", name: "accounts", type: "address[]" },
      ],
      name: "absorb",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "account", type: "address" }],
      name: "accrueAccount",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "manager", type: "address" },
        { internalType: "address", name: "asset", type: "address" },
        { internalType: "uint256", name: "amount", type: "uint256" },
      ],
      name: "approveThis",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "account", type: "address" }],
      name: "balanceOf",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "baseBorrowMin",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "baseMinForRewards",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "baseScale",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "baseToken",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "baseTokenPriceFeed",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "baseTrackingBorrowSpeed",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "baseTrackingSupplySpeed",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "account", type: "address" }],
      name: "borrowBalanceOf",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "borrowKink",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "borrowPerSecondInterestRateBase",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "borrowPerSecondInterestRateSlopeHigh",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "borrowPerSecondInterestRateSlopeLow",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "asset", type: "address" },
        { internalType: "uint256", name: "minAmount", type: "uint256" },
        { internalType: "uint256", name: "baseAmount", type: "uint256" },
        { internalType: "address", name: "recipient", type: "address" },
      ],
      name: "buyCollateral",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "decimals",
      outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "extensionDelegate",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint8", name: "i", type: "uint8" }],
      name: "getAssetInfo",
      outputs: [
        {
          components: [
            { internalType: "uint8", name: "offset", type: "uint8" },
            { internalType: "address", name: "asset", type: "address" },
            { internalType: "address", name: "priceFeed", type: "address" },
            { internalType: "uint64", name: "scale", type: "uint64" },
            {
              internalType: "uint64",
              name: "borrowCollateralFactor",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "liquidateCollateralFactor",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "liquidationFactor",
              type: "uint64",
            },
            { internalType: "uint128", name: "supplyCap", type: "uint128" },
          ],
          internalType: "struct CometCore.AssetInfo",
          name: "",
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "asset", type: "address" }],
      name: "getAssetInfoByAddress",
      outputs: [
        {
          components: [
            { internalType: "uint8", name: "offset", type: "uint8" },
            { internalType: "address", name: "asset", type: "address" },
            { internalType: "address", name: "priceFeed", type: "address" },
            { internalType: "uint64", name: "scale", type: "uint64" },
            {
              internalType: "uint64",
              name: "borrowCollateralFactor",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "liquidateCollateralFactor",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "liquidationFactor",
              type: "uint64",
            },
            { internalType: "uint128", name: "supplyCap", type: "uint128" },
          ],
          internalType: "struct CometCore.AssetInfo",
          name: "",
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "utilization", type: "uint256" },
      ],
      name: "getBorrowRate",
      outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "priceFeed", type: "address" }],
      name: "getPrice",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "getReserves",
      outputs: [{ internalType: "int256", name: "", type: "int256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "utilization", type: "uint256" },
      ],
      name: "getSupplyRate",
      outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "getUtilization",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "governor",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "owner", type: "address" },
        { internalType: "address", name: "manager", type: "address" },
      ],
      name: "hasPermission",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "initializeStorage",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "isAbsorbPaused",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "", type: "address" },
        { internalType: "address", name: "", type: "address" },
      ],
      name: "isAllowed",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "account", type: "address" }],
      name: "isBorrowCollateralized",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "isBuyPaused",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "account", type: "address" }],
      name: "isLiquidatable",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "isSupplyPaused",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "isTransferPaused",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "isWithdrawPaused",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "", type: "address" }],
      name: "liquidatorPoints",
      outputs: [
        { internalType: "uint32", name: "numAbsorbs", type: "uint32" },
        { internalType: "uint64", name: "numAbsorbed", type: "uint64" },
        { internalType: "uint128", name: "approxSpend", type: "uint128" },
        { internalType: "uint32", name: "_reserved", type: "uint32" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "numAssets",
      outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "bool", name: "supplyPaused", type: "bool" },
        { internalType: "bool", name: "transferPaused", type: "bool" },
        { internalType: "bool", name: "withdrawPaused", type: "bool" },
        { internalType: "bool", name: "absorbPaused", type: "bool" },
        { internalType: "bool", name: "buyPaused", type: "bool" },
      ],
      name: "pause",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "pauseGuardian",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "asset", type: "address" },
        { internalType: "uint256", name: "baseAmount", type: "uint256" },
      ],
      name: "quoteCollateral",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "storeFrontPriceFactor",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "asset", type: "address" },
        { internalType: "uint256", name: "amount", type: "uint256" },
      ],
      name: "supply",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "from", type: "address" },
        { internalType: "address", name: "dst", type: "address" },
        { internalType: "address", name: "asset", type: "address" },
        { internalType: "uint256", name: "amount", type: "uint256" },
      ],
      name: "supplyFrom",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "supplyKink",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "supplyPerSecondInterestRateBase",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "supplyPerSecondInterestRateSlopeHigh",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "supplyPerSecondInterestRateSlopeLow",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "dst", type: "address" },
        { internalType: "address", name: "asset", type: "address" },
        { internalType: "uint256", name: "amount", type: "uint256" },
      ],
      name: "supplyTo",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "targetReserves",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "totalBorrow",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "totalSupply",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "", type: "address" }],
      name: "totalsCollateral",
      outputs: [
        { internalType: "uint128", name: "totalSupplyAsset", type: "uint128" },
        { internalType: "uint128", name: "_reserved", type: "uint128" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "trackingIndexScale",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "dst", type: "address" },
        { internalType: "uint256", name: "amount", type: "uint256" },
      ],
      name: "transfer",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "dst", type: "address" },
        { internalType: "address", name: "asset", type: "address" },
        { internalType: "uint256", name: "amount", type: "uint256" },
      ],
      name: "transferAsset",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "src", type: "address" },
        { internalType: "address", name: "dst", type: "address" },
        { internalType: "address", name: "asset", type: "address" },
        { internalType: "uint256", name: "amount", type: "uint256" },
      ],
      name: "transferAssetFrom",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "src", type: "address" },
        { internalType: "address", name: "dst", type: "address" },
        { internalType: "uint256", name: "amount", type: "uint256" },
      ],
      name: "transferFrom",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "", type: "address" }],
      name: "userBasic",
      outputs: [
        { internalType: "int104", name: "principal", type: "int104" },
        { internalType: "uint64", name: "baseTrackingIndex", type: "uint64" },
        { internalType: "uint64", name: "baseTrackingAccrued", type: "uint64" },
        { internalType: "uint16", name: "assetsIn", type: "uint16" },
        { internalType: "uint8", name: "_reserved", type: "uint8" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "", type: "address" },
        { internalType: "address", name: "", type: "address" },
      ],
      name: "userCollateral",
      outputs: [
        { internalType: "uint128", name: "balance", type: "uint128" },
        { internalType: "uint128", name: "_reserved", type: "uint128" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "", type: "address" }],
      name: "userNonce",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "asset", type: "address" },
        { internalType: "uint256", name: "amount", type: "uint256" },
      ],
      name: "withdraw",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "src", type: "address" },
        { internalType: "address", name: "to", type: "address" },
        { internalType: "address", name: "asset", type: "address" },
        { internalType: "uint256", name: "amount", type: "uint256" },
      ],
      name: "withdrawFrom",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "to", type: "address" },
        { internalType: "uint256", name: "amount", type: "uint256" },
      ],
      name: "withdrawReserves",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "to", type: "address" },
        { internalType: "address", name: "asset", type: "address" },
        { internalType: "uint256", name: "amount", type: "uint256" },
      ],
      name: "withdrawTo",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
  ],
};
