const SOLANA_USDC_ADDR = '5uBU2zUG8xTLA6XwwcTFWib1p7EjCBzWbiy44eVASTfV';
const SOLANA_USDT_ADDR = 'Hv7yPYnGs6fpN3o1NZvkima9mKDrRDJtNxf23oKLCjau';
const ETH_USDC_ADDR = '4R6b4aibi46JzAnuA8ZWXrHAsR1oZBTZ8dqkuer3LsbS';
const ETH_USDT_ADDR = '2DMUL42YEb4g1HAKXhUxL3Yjfgoj4VvRqKwheorfFcPV';
const BSC_USD_ADDR = 'DukQAFyxR41nbbq2FBUDMyrtF2CRmWBREjZaTVj4u9As';
const BSC_USDT_ADDR = '9KMH3p8cUocvQRbJfKRAStKG52xCCWNmEPsJm5gc8fzw';
const USDC_PYTH_ADDR = 'Gnt27xtC473ZT2Mw5u8wZ68Z3gULkSTb5DuxJy7eJotD';
const USDT_PYTH_ADDR = '3vxLXJqLqF3JG5TCbYycbKWRBbCJQLxQmBGCkyqEEefL';

module.exports = { 
	SOLANA_USDC_ADDR,
	SOLANA_USDT_ADDR,
	ETH_USDC_ADDR,
	ETH_USDT_ADDR,
	BSC_USD_ADDR,
	BSC_USDT_ADDR,
	USDC_PYTH_ADDR,
	USDT_PYTH_ADDR,
}
