const SOLANA_USDC_ADDR = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
const SOLANA_USDT_ADDR = 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB';
const ETH_USDC_ADDR = 'A9mUU4qviSctJVPJdBJWkb28deg915LYJKrzQ19ji3FM';
const ETH_USDT_ADDR = 'Dn4noZ5jgGfkntzcQSUZ8czkreiZ1ForXYoV2H8Dm7S1';
const BSC_USD_ADDR = '5RpUwQ8wtdPCZHhu6MERp2RGrpobsbZ6MH5dDHkUjs2';
const BSC_USDT_ADDR = '8qJSyQprMC57TWKaYEmetUR3UUiTP2M3hXdcvFhkZdmv';

module.exports = { 
	SOLANA_USDC_ADDR,
	SOLANA_USDT_ADDR,
	ETH_USDC_ADDR,
	ETH_USDT_ADDR,
	BSC_USD_ADDR,
	BSC_USDT_ADDR,
}
