const SOLANA_USDC_ADDR = '5uBU2zUG8xTLA6XwwcTFWib1p7EjCBzWbiy44eVASTfV';
const SOLANA_USDT_ADDR = 'Hv7yPYnGs6fpN3o1NZvkima9mKDrRDJtNxf23oKLCjau';
const ETH_USDC_ADDR = '4R6b4aibi46JzAnuA8ZWXrHAsR1oZBTZ8dqkuer3LsbS';
const ETH_USDT_ADDR = '2DMUL42YEb4g1HAKXhUxL3Yjfgoj4VvRqKwheorfFcPV';
const BSC_USD_ADDR = 'DukQAFyxR41nbbq2FBUDMyrtF2CRmWBREjZaTVj4u9As';
const BSC_USDT_ADDR = '9KMH3p8cUocvQRbJfKRAStKG52xCCWNmEPsJm5gc8fzw';
const AVAX_USDC_ADDR = '9RgAUVyd72THEnLLwZswBbc2VpmJnSPP9R91ZVxjq1rv';
const AVAX_USDC_SWIM_USD_ADDR = '6zbeCeeUGbjiiW9PpxVuMqLmWZowoaDsMmWtRmX5Nx5W';
const AVAX_USDT_ADDR = '52q1M9ceJozzfGTgD5wx6K2WQjvQnUpF3uKmWzdy73ER';
const AVAX_USDT_SWIM_USD_ADDR = '9QAFkr2tYntkeiWFS6KJYYBFLeKh6CBTqUwhCCBdhdbV';
const POLYGON_USDC_ADDR = 'DwjutE8CB1WNUzy78f44BdJNWMF1pYC5wd6eTchRcacL';
const POLYGON_USDC_SWIM_USD_ADDR = '9MQ6FFBm7Nk9jMY65m8MYvsno2akEGPLMLjargoccvic';
const POLYGON_USDT_ADDR = 'A4KTWbPgxUeLWJdXyqsc7tV2GgkxW5gaKeHvKz3LLght';
const POLYGON_USDT_SWIM_USD_ADDR = 'BBHCpu6xKDjvoUDTBmBmejAoN4ADNeZiYcvKfVv7yz3L';

module.exports = { 
	SOLANA_USDC_ADDR,
	SOLANA_USDT_ADDR,
	ETH_USDC_ADDR,
	ETH_USDT_ADDR,
	BSC_USD_ADDR,
	BSC_USDT_ADDR,
	AVAX_USDC_ADDR,
	AVAX_USDC_SWIM_USD_ADDR,
	AVAX_USDT_ADDR,
	AVAX_USDT_SWIM_USD_ADDR,
	POLYGON_USDC_ADDR,
	POLYGON_USDC_SWIM_USD_ADDR,
	POLYGON_USDT_ADDR,
	POLYGON_USDT_SWIM_USD_ADDR,
}
