name: Test_Change
on:
  pull_request

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@ce38c8ce2459ca3c303415eec8cb0409857b4272
        with:
          output: 'json'
          fileOutput: 'json'

      - name: Setup Node.js with pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Run changes files through test script
        env:
          LLAMA_DEBUG_MODE: "true"
          FILES_MODIFIED: ${{ steps.file_changes.outputs.files_modified }}
          FILES_ADDED: ${{ steps.file_changes.outputs.files_added }}
          WORKSPACE: ${{ github.workspace }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          RUN_FILES=$(
            MODIFIED="$FILES_MODIFIED" \
            ADDED="$FILES_ADDED" \
            node "$WORKSPACE"/.github/workflows/getFileList.js
          )

          if [ "$RUN_FILES" = "[]" ]; then
            echo "No adapter files were modified"
            exit 0
          fi

          # pnpm remove typescript @types/async-retry @types/bn.js ts-node @solendprotocol/solend-sdk @hover-labs/kolibri-js

          # fail if package.json or package-lock.json is changed
          if [[ "$FILES_MODIFIED" == *"package.json"* || "$FILES_MODIFIED" == *"package-lock.json"* ]]; then
            echo "------ ERROR ------ > Please revert changes to package.json / package-lock.json" > /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/output.txt
            node "$WORKSPACE"/.github/workflows/commentResult.js /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/output.txt "$REPO_OWNER" "$REPO_NAME" "$PR_NUMBER"
            exit 1
          fi

          for i in $(echo $RUN_FILES | tr  -d '"[]' | tr "," "\n")
          do
            {
              node "$WORKSPACE"/test.js "$WORKSPACE"/${i} 2>&1 | tee output.txt
              node "$WORKSPACE"/.github/workflows/commentResult.js /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/output.txt "$REPO_OWNER" "$REPO_NAME" "$PR_NUMBER" ${i}
              if grep -q "\-\-\-\- ERROR \-\-\-\-" output.txt; then
                exit 1;
              fi
            } || {
              echo -n $i
              echo ' doesnt run'
            }
          done

      - name: Run ESLint
        run: |
          npm run lint
